# Loan Microservice runs on port 8081
# We need a different port because Account service already uses default 8080.
# If we try to start Loan on 8080 it will fail with "Address already in use" error.
server.port=8081

logging.level.com.cognizant=debug
